### ISSUE TITLE
Has anyone encountered issues while downloading the Epic-Kitchens-100 dataset? The download speed is too slow, is there a mirror site available?

### ISSUE THREAD

**Issue by Old-Lorry** [ChenYi99/EgoPlan#10]

**Comment by ChenYi99** [comment]
You can try the following download link:

https://www.alipan.com/t/77Aaru1G6VYGeGI0oLsW

**Comment by Old-Lorry** [comment]
Thank you very much for your reply and for providing the data! Could you share more detailed experiences? For example, how did you initially download it, and how long did it take?

**Comment by ChenYi99** [comment]
I directly used the data available in our lab, so I'm unsure of the exact time for downloading it. The downloading speed may depend on the network situation.

**Comment by Old-Lorry** [comment]
Thank you so much! I download the dataset 1mb/s, while it's 2TB! Thank you for your data!
