### ISSUE TITLE
Regarding downloading the Ego4D dataset

### ISSUE THREAD

**Issue by takenpeanut** [ChenYi99/EgoPlan#4]
should I download the full video dataset (namely using `--datasets full_scale annotations`) or just a subset of it?

**Comment by ChenYi99** [comment]
We only use a portion of the videos from the Epic-Kitchens-100 and Ego4D datasets. You can determine which videos are needed for the training and validation sets by referring to the "video_id" field in our data samples. Additionally, please note that we directly use the officially released RGB frames instead of raw videos for Epic-Kitchens.

**Comment by zulihit** [comment]
Hi, I have the same question? Can I understand it this way that I only need to download the data in P01 and the data in v1_288p?

EPIC-KITCHENS
└── P01
    └── rgb_frames
        └── P01_01
            ├── frame_0000000001.jpg
            └── ...
Ego4D
└──v1_288p
    ├── 000786a7-3f9d-4fe6-bfb3-045b368f7d44.mp4
    └── ...

> 我们仅使用 Epic-Kitchens-100 和 Ego4D 数据集中的部分视频。您可以通过参考我们数据样本中的“video_id”字段来确定训练集和验证集需要哪些视频。此外，请注意，我们直接使用官方发布的 RGB 帧而不是 Epic-Kitchens 的原始视频。

**Comment by zulihit** [comment]
Hi, I have the same question? Can I understand it this way that I only need to download the data in P01 and the data in v1_288p?

EPIC-KITCHENS
└── P01
    └── rgb_frames
        └── P01_01
            ├── frame_0000000001.jpg
            └── ...
Ego4D
└──v1_288p
    ├── 000786a7-3f9d-4fe6-bfb3-045b368f7d44.mp4
    └── ...

> We only use a portion of the videos from the Epic-Kitchens-100 and Ego4D datasets. You can determine which videos are needed for the training and validation sets by referring to the "video_id" field in our data samples. Additionally, please note that we directly use the officially released RGB frames instead of raw videos for Epic-Kitchens.

**Comment by zulihit** [comment]
Can you provide more detailed explanations on which part and how to download Ego4D? Thank you very much for your contribution.

**Comment by ChenYi99** [comment]
Apologies for the confusion. You need to download the pre-extracted RGB frames data from all the participants in Epic-Kitchens, not just P01. Similarly, you need to download the v1_288p version of videos from Ego4D. 

As for which specific video corresponding data you need to download, you can refer to the video_id field of [our data samples](https://github.com/ChenYi99/EgoPlan/tree/challenge?tab=readme-ov-file#egoplan-validation-and-test-datasets) for download (for instance, PXX_YY is the style of video_id in Epic-Kitchens, where XX represents the participant number and YY the video number, and 000786a7-3f9d-4fe6-bfb3-045b368f7d44 is the style of video_id in Ego4D).

**Comment by ChenYi99** [comment]
You can follow this [page ](https://ego4d-data.org/docs/start-here/) to download the Ego4D dataset. The more detailed document can be found [here](https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md). 

After [signing Ego4D license](https://ego4ddataset.com/) and [downloading the CLI](https://ego4d-data.org/docs/start-here/#cli-download). You can run the following command to download the full-scale videos of version 1:

```
ego4d --output_directory="~/ego4d_data" --datasets full_scale --metadata --version v1
```

Additionally, you can specify video UIDs using the ["--video_uids" flag](https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md#detailed-flags) to reduce the download size.

**Comment by takenpeanut** [comment]
> You can follow this [page ](https://ego4d-data.org/docs/start-here/) to download the Ego4D dataset. The more detailed document can be found [here](https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md).
> 
> After [signing Ego4D license](https://ego4ddataset.com/) and [downloading the CLI](https://ego4d-data.org/docs/start-here/#cli-download). You can run the following command to download the full-scale videos of version 1:
> 
> ```
> ego4d --output_directory="~/ego4d_data" --datasets full_scale --metadata --version v1
> ```
> 
> Additionally, you can specify video UIDs using the ["--video_uids" flag](https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md#detailed-flags) to reduce the download size.

Thanks for the clarification!

**Comment by takenpeanut** [comment]
Thanks for the clarification!
