### ISSUE TITLE
Address error

### ISSUE THREAD

**Issue by JZXXX** [ChenYi99/EgoPlan#5]
Can not find VIT ([eva_vit_g.pth](https://link.zhihu.com/?target=https%3A//storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pt)).

**Comment by ChenYi99** [comment]
Sorry, the link should be [https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth](https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth)
